/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectRestaurant;




/**
 *
 * @author james
 */
public class LoginEmployer extends javax.swing.JFrame {

    /**
     * Creates new form LoginEmployer
     */
    public LoginEmployer() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Error = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelLogE = new javax.swing.JPanel();
        iconLog = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        boxTextLog = new javax.swing.JTextField();
        labelPassw = new javax.swing.JLabel();
        boxPassLog = new javax.swing.JPasswordField();
        labelChangeA = new javax.swing.JLabel();
        loginButtom = new javax.swing.JButton();
        acountButtom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        Error.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ErrorComponentAdded(evt);
            }
        });

        jLabel7.setText("Error");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel7)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ErrorLayout = new javax.swing.GroupLayout(Error.getContentPane());
        Error.getContentPane().setLayout(ErrorLayout);
        ErrorLayout.setHorizontalGroup(
            ErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        ErrorLayout.setVerticalGroup(
            ErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        panelLogE.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        panelLogE.setForeground(new java.awt.Color(255, 255, 255));
        panelLogE.setToolTipText("");
        panelLogE.setAutoscrolls(true);
        panelLogE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emoployer.png"))); // NOI18N
        panelLogE.add(iconLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 141, -1));

        labelUser.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        labelUser.setText("Usuario");
        panelLogE.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        boxTextLog.setBackground(new java.awt.Color(255, 255, 255));
        boxTextLog.setForeground(new java.awt.Color(0, 0, 0));
        boxTextLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTextLogActionPerformed(evt);
            }
        });
        panelLogE.add(boxTextLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 34));

        labelPassw.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        labelPassw.setText("Contraseña");
        panelLogE.add(labelPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        boxPassLog.setBackground(new java.awt.Color(255, 255, 255));
        boxPassLog.setForeground(new java.awt.Color(0, 0, 0));
        panelLogE.add(boxPassLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 280, 34));

        labelChangeA.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        labelChangeA.setText("Cambio de rol");
        panelLogE.add(labelChangeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        loginButtom.setBackground(new java.awt.Color(102, 102, 102));
        loginButtom.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginButtom.setText("Ingresar");
        loginButtom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButtom.setVerifyInputWhenFocusTarget(false);
        loginButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtomActionPerformed(evt);
            }
        });
        panelLogE.add(loginButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 64, -1));

        acountButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER change.png"))); // NOI18N
        acountButtom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acountButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acountButtomActionPerformed(evt);
            }
        });
        panelLogE.add(acountButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 80, 70));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("@ligth System");
        panelLogE.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 240, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel3.setMinimumSize(new java.awt.Dimension(0, 0));
        panelLogE.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 480, 380));

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setText("Eres Administrador? Prueba cambiar de rol");
        panelLogE.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, 40));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel5.setText("Welcome to");
        panelLogE.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 191, 40));

        jLabel4.setFont(new java.awt.Font("Colonna MT", 0, 36)); // NOI18N
        jLabel4.setText("KongRestaurant ");
        panelLogE.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 280, 90));
        panelLogE.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 140, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogE, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogE, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acountButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acountButtomActionPerformed
     
        changeUser();
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_acountButtomActionPerformed

    private void loginButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtomActionPerformed
     
        systemLog();

    }//GEN-LAST:event_loginButtomActionPerformed

    private void boxTextLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTextLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTextLogActionPerformed

    private void ErrorComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ErrorComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorComponentAdded
public void systemLog(){
  
String user = boxTextLog.getText();

String password = String.valueOf(boxPassLog.getPassword());
    if ((user.equals("User123"))&&(password.compareTo("1234")==0)) {
        
//JOptionPane.showMessageDialog(null,"Bienvenido al Sistema");
System form = new System();
        form.setVisible(true);
        
     
        this.dispose();
    } else {
//         JOptionPane.showMessageDialog(null,"Error vuelva a intentarlo"); 
         boxPassLog.setText("");
         boxTextLog.setText(null);
    }




}
public void changeUser(){


LoginAdmin form = new LoginAdmin();
        form.setVisible(true);
        
     
        this.dispose();



}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEmployer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Error;
    private javax.swing.JButton acountButtom;
    private javax.swing.JPasswordField boxPassLog;
    private javax.swing.JTextField boxTextLog;
    private javax.swing.JLabel iconLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelChangeA;
    private javax.swing.JLabel labelPassw;
    private javax.swing.JLabel labelUser;
    private javax.swing.JButton loginButtom;
    private javax.swing.JPanel panelLogE;
    // End of variables declaration//GEN-END:variables

 
}
