/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CesarYsusInterfases;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Cesar
 */
public class InterfaceChargeMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterfaceChargeMenu
     */
    public InterfaceChargeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BgPanel = new javax.swing.JPanel();
        BorderPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lblMenuCharge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taShowMenu = new javax.swing.JTextArea();
        btnMenuElection = new javax.swing.JButton();
        lblChargeMenu = new javax.swing.JLabel();
        btnSaveElection = new javax.swing.JButton();
        lblSaveElecction1 = new javax.swing.JLabel();
        btnDeleteElection = new javax.swing.JButton();
        lblDeleteElecction = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BorderPanel.setBackground(new java.awt.Color(51, 51, 51));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CesarYsusInterfases/salida.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblMenuCharge.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMenuCharge.setForeground(new java.awt.Color(0, 153, 153));
        lblMenuCharge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuCharge.setText("Cargar Menu");
        lblMenuCharge.setOpaque(true);

        javax.swing.GroupLayout BorderPanelLayout = new javax.swing.GroupLayout(BorderPanel);
        BorderPanel.setLayout(BorderPanelLayout);
        BorderPanelLayout.setHorizontalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(lblMenuCharge)
                .addGap(240, 240, 240))
        );
        BorderPanelLayout.setVerticalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addComponent(lblMenuCharge)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BgPanel.add(BorderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        taShowMenu.setColumns(20);
        taShowMenu.setRows(5);
        taShowMenu.setText("\t\t\t      Menu del dia");
        jScrollPane1.setViewportView(taShowMenu);

        BgPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 540, 390));

        btnMenuElection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CesarYsusInterfases/carga-de-carpeta (1).png"))); // NOI18N
        btnMenuElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuElectionActionPerformed(evt);
            }
        });
        BgPanel.add(btnMenuElection, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 80));

        lblChargeMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblChargeMenu.setText("Cargar menu");
        BgPanel.add(lblChargeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnSaveElection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CesarYsusInterfases/flecha-de-circulo-de-disquete-a-la-derecha.png"))); // NOI18N
        btnSaveElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveElectionActionPerformed(evt);
            }
        });
        BgPanel.add(btnSaveElection, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 70));

        lblSaveElecction1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSaveElecction1.setText("Guardar eleccion");
        BgPanel.add(lblSaveElecction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btnDeleteElection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CesarYsusInterfases/circulo-de-basura.png"))); // NOI18N
        btnDeleteElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteElectionActionPerformed(evt);
            }
        });
        BgPanel.add(btnDeleteElection, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 80));

        lblDeleteElecction.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDeleteElecction.setText("Borrar eleccion ");
        BgPanel.add(lblDeleteElecction, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        getContentPane().add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveElectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveElectionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ActionListener closeSystem = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Cierra la ventana actual
            }
        };
        // Asignar el detector de acción al botón
        btnExit.addActionListener(closeSystem);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDeleteElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteElectionActionPerformed
taShowMenu.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteElectionActionPerformed

    private void btnMenuElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuElectionActionPerformed
        // Crear el diálogo de selección de archivo
        JFileChooser fileChooser = new JFileChooser();

        // Mostrar el diálogo y obtener el resultado
        int result = fileChooser.showOpenDialog(this);

        // Verificar si el usuario ha seleccionado un archivo
        if (result == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File file = fileChooser.getSelectedFile();

            // Leer el contenido del archivo
            try {
                BufferedReader reader = new BufferedReader(new FileReader(file));
                String line;
                StringBuilder content = new StringBuilder();
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n");
                }
                reader.close();
                // Hacer algo con el contenido del archivo (por ejemplo, mostrarlo en un JTextArea)
                taShowMenu.setText(content.toString());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnMenuElectionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel;
    private javax.swing.JPanel BorderPanel;
    private javax.swing.JButton btnDeleteElection;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMenuElection;
    private javax.swing.JButton btnSaveElection;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChargeMenu;
    private javax.swing.JLabel lblDeleteElecction;
    private javax.swing.JLabel lblMenuCharge;
    private javax.swing.JLabel lblSaveElecction1;
    private javax.swing.JTextArea taShowMenu;
    // End of variables declaration//GEN-END:variables
}
