package interfazMesero;

import Mesero.Order;

/**
 *
 * @author Jorshua Solorzano
 */

public class AccompanimentsMenu extends javax.swing.JInternalFrame {

    private String selectedAccompaniments;
    private int quantityAccompaniments;
    private Order Order;

    public AccompanimentsMenu() {
        super("Menú de acompañamientos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAccompaniaments = new javax.swing.JComboBox<>();
        spnAccompaniaments = new javax.swing.JSpinner();
        lblMainDishes = new javax.swing.JLabel();
        btnPrintAccompaniaments = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(455, 657));

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbAccompaniaments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Pure de Papas", "Ensalada Cesar", "Ensalada Rusa", "Ensalada Verde", "Ceviche de pescado", "Ceviche de camarones", "Ceviche de platano verde", "Caracolitos con atún", "Verduras a la mantequilla", "Orden de papas fritas", "Frijoles fritos" }));
        cmbAccompaniaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccompaniamentsActionPerformed(evt);
            }
        });

        spnAccompaniaments.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblMainDishes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMainDishes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainDishes.setText("Acompañamientos");

        btnPrintAccompaniaments.setText("Imprimir pedido");
        btnPrintAccompaniaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAccompaniamentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbAccompaniaments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnAccompaniaments, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnPrintAccompaniaments)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAccompaniaments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAccompaniaments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addComponent(btnPrintAccompaniaments)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAccompaniamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccompaniamentsActionPerformed

    }//GEN-LAST:event_cmbAccompaniamentsActionPerformed

    private void btnPrintAccompaniamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAccompaniamentsActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        selectedAccompaniments = (String) cmbAccompaniaments.getSelectedItem();
        quantityAccompaniments = (int) spnAccompaniaments.getValue();

        // Verificar si el JFrame InterPedido ya está creado
        if (Order != null) {
            // Construir el text a agregar
            String text = "Acompañamiento seleccionado: " + selectedAccompaniments + "\n";
            text += "Cantidad de acompañamientos: " + quantityAccompaniments + "\n";

            // Agregar el text al JTextArea txtPedido en el JFrame InterPedido
            Order.addText(text);
        }
    }//GEN-LAST:event_btnPrintAccompaniamentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintAccompaniaments;
    private javax.swing.JComboBox<String> cmbAccompaniaments;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMainDishes;
    private javax.swing.JSpinner spnAccompaniaments;
    // End of variables declaration//GEN-END:variables
}
