package interfazMesero;

import Mesero.Order;

/**
 *
 * @author Jorshua Solorzano
 */
public class AlcoholicDrinksMenu extends javax.swing.JInternalFrame {

    private String selectedAlcoholicDrinks;
    private int quantityAlcoholicDrinks;
    private Order Order;

    public AlcoholicDrinksMenu() {
        super("Menú de bebidas alcoholicas");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAlcoholicDrinks = new javax.swing.JComboBox<>();
        spnAlcoholicDrinks = new javax.swing.JSpinner();
        lblAlcoholicDrinks = new javax.swing.JLabel();
        btnPrintAlcoholicDrinks = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(455, 657));

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbAlcoholicDrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Margarita", "Martini", "Mojito ", "Sangria ", "Chiliguaro ", "Piña colada ", "Tequila ", "Ron ", "Cerveza Heineken ", "Cerveza Imperial ", "Cerveza Pilsen ", "Cerveza Corona ", "Vino tinto", "Vino blanco" }));
        cmbAlcoholicDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlcoholicDrinksActionPerformed(evt);
            }
        });

        spnAlcoholicDrinks.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblAlcoholicDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAlcoholicDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlcoholicDrinks.setText("Bebidas alcoholicas");

        btnPrintAlcoholicDrinks.setText("Imprimir pedido");
        btnPrintAlcoholicDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAlcoholicDrinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(cmbAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnPrintAlcoholicDrinks)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(btnPrintAlcoholicDrinks)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlcoholicDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlcoholicDrinksActionPerformed

    }//GEN-LAST:event_cmbAlcoholicDrinksActionPerformed

    private void btnPrintAlcoholicDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAlcoholicDrinksActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        selectedAlcoholicDrinks = (String) cmbAlcoholicDrinks.getSelectedItem();
        quantityAlcoholicDrinks = (int) spnAlcoholicDrinks.getValue();

        // Verificar si el JFrame InterPedido ya está creado
        if (Order != null) {
            // Construir el text a agregar
            String text = "Bibidas alcoholicas seleccionadas: " + selectedAlcoholicDrinks + "\n";
            text += "Cantidad de bebidas alcoholicas: " + quantityAlcoholicDrinks + "\n";

            // Agregar el text al JTextArea txtPedido en el JFrame InterPedido
            Order.addText(text);
        }
    }//GEN-LAST:event_btnPrintAlcoholicDrinksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintAlcoholicDrinks;
    private javax.swing.JComboBox<String> cmbAlcoholicDrinks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlcoholicDrinks;
    private javax.swing.JSpinner spnAlcoholicDrinks;
    // End of variables declaration//GEN-END:variables
}
