/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfazMesero;

/**
 *
 * @author Jorshua Solorzano
 */
public class MenuAlcoholicas extends javax.swing.JInternalFrame {

    private String bebidaAlcoSeleccionado;
    private int cantidadAlcoholicas;
    private Pedido Pedido;

    public MenuAlcoholicas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAlcoholicas = new javax.swing.JComboBox<>();
        spnAlcoholicas = new javax.swing.JSpinner();
        lblAlcoholicas = new javax.swing.JLabel();
        btnImprimirAlcoholicas = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbAlcoholicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Arroz con camarones", "Arroz con pollo", "Casado de carne en salsa" }));
        cmbAlcoholicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlcoholicasActionPerformed(evt);
            }
        });

        spnAlcoholicas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblAlcoholicas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAlcoholicas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlcoholicas.setText("Bebidas Alcoholicas");

        btnImprimirAlcoholicas.setText("Imprimir");
        btnImprimirAlcoholicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirAlcoholicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnImprimirAlcoholicas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(cmbAlcoholicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(spnAlcoholicas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblAlcoholicas)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblAlcoholicas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlcoholicas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAlcoholicas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnImprimirAlcoholicas)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlcoholicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlcoholicasActionPerformed

    }//GEN-LAST:event_cmbAlcoholicasActionPerformed

    private void btnImprimirAlcoholicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirAlcoholicasActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        bebidaAlcoSeleccionado = (String) cmbAlcoholicas.getSelectedItem();
        cantidadAlcoholicas = (int) spnAlcoholicas.getValue();
        // Verificar si el JFrame InterPedido ya está creado
        if (Pedido != null) {
            // Construir el texto a agregar
            String texto = "Bebidas Alcoholicas seleccionadas: " + bebidaAlcoSeleccionado + "\n";
            texto += "Cantidad de bebidas alcoholicas: " + cantidadAlcoholicas + "\n";

            // Agregar el texto al JTextArea txtPedido en el JFrame InterPedido
            Pedido.agregarTexto(texto);
        }
    }//GEN-LAST:event_btnImprimirAlcoholicasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirAlcoholicas;
    private javax.swing.JComboBox<String> cmbAlcoholicas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlcoholicas;
    private javax.swing.JSpinner spnAlcoholicas;
    // End of variables declaration//GEN-END:variables
}
