/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfazMesero;

/**
 *
 * @author Jorshua Solorzano
 */
public class MenuPlatosFuertes extends javax.swing.JInternalFrame {

    private String platoFuerteSeleccionado;
    private int cantidadPlatosFuertes;
    private Pedido Pedido;

    public MenuPlatosFuertes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbPlatoFuerte = new javax.swing.JComboBox<>();
        spnPlatoFuerte = new javax.swing.JSpinner();
        lblPlatoFuerte = new javax.swing.JLabel();
        btnImprimirPlatoFuerte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setFocusable(false);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(389, 536));

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbPlatoFuerte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Arroz con camarones", "Arroz con pollo", "Casado de carne en salsa" }));
        cmbPlatoFuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlatoFuerteActionPerformed(evt);
            }
        });

        spnPlatoFuerte.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblPlatoFuerte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlatoFuerte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlatoFuerte.setText("Platos fuertes");

        btnImprimirPlatoFuerte.setText("Imprimir");
        btnImprimirPlatoFuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPlatoFuerteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnImprimirPlatoFuerte))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(cmbPlatoFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(spnPlatoFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblPlatoFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblPlatoFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlatoFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPlatoFuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnImprimirPlatoFuerte)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPlatoFuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlatoFuerteActionPerformed

    }//GEN-LAST:event_cmbPlatoFuerteActionPerformed

    private void btnImprimirPlatoFuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPlatoFuerteActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        platoFuerteSeleccionado = (String) cmbPlatoFuerte.getSelectedItem();
        cantidadPlatosFuertes = (int) spnPlatoFuerte.getValue();

        // Verificar si el JFrame InterPedido ya está creado
        if (Pedido != null) {
            // Construir el texto a agregar
            String texto = "Plato fuerte seleccionado: " + platoFuerteSeleccionado + "\n";
            texto += "Cantidad de platos fuertes: " + cantidadPlatosFuertes + "\n";

            // Agregar el texto al JTextArea txtPedido en el JFrame InterPedido
            Pedido.agregarTexto(texto);
        }
    }//GEN-LAST:event_btnImprimirPlatoFuerteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirPlatoFuerte;
    private javax.swing.JComboBox<String> cmbPlatoFuerte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPlatoFuerte;
    private javax.swing.JSpinner spnPlatoFuerte;
    // End of variables declaration//GEN-END:variables
}
