/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfazMesero;

/**
 *
 * @author Jorshua Solorzano
 */
public class MenuRefrescos extends javax.swing.JInternalFrame {

    private String refrescoSeleccionado;
    private int cantidadRefrescos;
    private Pedido Pedido;

    public MenuRefrescos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbRefresco = new javax.swing.JComboBox<>();
        spnRefresco = new javax.swing.JSpinner();
        lblRefresco = new javax.swing.JLabel();
        btnImprimirRefresco = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbRefresco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Arroz con camarones", "Arroz con pollo", "Casado de carne en salsa" }));
        cmbRefresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRefrescoActionPerformed(evt);
            }
        });

        spnRefresco.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblRefresco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRefresco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresco.setText("Refrescos");

        btnImprimirRefresco.setText("Imprimir");
        btnImprimirRefresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRefrescoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnImprimirRefresco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(cmbRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(spnRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnImprimirRefresco)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRefrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRefrescoActionPerformed

    }//GEN-LAST:event_cmbRefrescoActionPerformed

    private void btnImprimirRefrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRefrescoActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        refrescoSeleccionado = (String) cmbRefresco.getSelectedItem();
        cantidadRefrescos = (int) spnRefresco.getValue();

        // Verificar si el JFrame InterPedido ya está creado
        if (Pedido != null) {
            // Construir el texto a agregar
            String texto = "Refresco seleccionado: " + refrescoSeleccionado + "\n";
            texto += "Cantidad de refrescos: " + cantidadRefrescos + "\n";

            // Agregar el texto al JTextArea txtPedido en el JFrame InterPedido
            Pedido.agregarTexto(texto);
        }
    }//GEN-LAST:event_btnImprimirRefrescoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirRefresco;
    private javax.swing.JComboBox<String> cmbRefresco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRefresco;
    private javax.swing.JSpinner spnRefresco;
    // End of variables declaration//GEN-END:variables
}
