package interfazMesero;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Jorshua Solorzano
 */
public class Pedido extends javax.swing.JFrame implements ActionListener {

    public Pedido() {
        super("Punto de venta makacos restaurant");
        initComponents();
        String[] menuEats = {"Hamburguesa", "Pizza", "Ensalada", "Sopa"};
        cmbAlimentos = new JComboBox<>();
        // Crear el modelo de combo box y asignar el vector de cadenas
        DefaultComboBoxModel<String> eats = new DefaultComboBoxModel<>(menuEats);
        // Asignar el modelo al combo box
        cmbAlimentos.setModel(eats);
        cmbAlimentos.addActionListener(this);
        
        String[] menuDrinks = {"Vino", "Cerveza", "Ron", "Coca cola"};
        cmbBebidas = new JComboBox<>();
        // Crear el modelo de combo box y asignar el vector de cadenas
        DefaultComboBoxModel<String> drinks = new DefaultComboBoxModel<>(menuDrinks);
        // Asignar el modelo al combo box
        cmbBebidas.setModel(drinks);
        cmbBebidas.addActionListener(this);
        
        btnEnviarCocina.addActionListener(this);
        btnEnviarBar.addActionListener(this);
        
        pack();
        setVisible(false);

    }

    public void actionPerformed(ActionEvent e) {
        // Maneja los eventos del botón
        if (e.getSource() == btnEnviarCocina) {
            enviarPedido("cocina");
        } else if (e.getSource() == btnEnviarBar) {
            enviarPedido("bar");
        } else if (e.getSource() == cmbAlimentos) {
            String selectedItem = cmbAlimentos.getSelectedItem().toString();
            txtAlimentos.append(selectedItem + "\n");
        } else if (e.getSource() == cmbBebidas) {
            String selectedItem = cmbBebidas.getSelectedItem().toString();
            txtBebidas.append(selectedItem + "\n");
        }     
    }

    private void enviarPedido(String destino) {
        // Obtener el nombre del cliente y pedidos
        String nombreCliente = txtNombreCliente.getText();
        String pedidoAlimentos = txtAlimentos.getText();
        String pedidoBebidas = txtBebidas.getText();
        
        // Enviar los pedidos al destino seleccionado
        if (destino.equals("Cocina")) {
            java.lang.System.out.println("Pedido para " + nombreCliente + " enviado a la cocina: " + pedidoAlimentos);
            guardarPedido("Cocina", nombreCliente, pedidoAlimentos);
        } else if (destino.equals("Bar")) {
            java.lang.System.out.println("Pedido para " + nombreCliente + " enviado al bar: " + pedidoBebidas);
            guardarPedido("Bar", nombreCliente, pedidoAlimentos);
        }
        
    }

    private void guardarPedido(String destino, String nombreCliente, String pedido) {
        // Guardar el pedido en un archivo de texto para el historial
        try {
            FileWriter writer = new FileWriter("historial_pedidos.txt", true);
            writer.write(destino + "," + nombreCliente + "," + pedido);
            writer.close();
        } catch (IOException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void initcomponents(){
    initcomponents();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        cmbAlimentos = new javax.swing.JComboBox<>();
        cmbBebidas = new javax.swing.JComboBox<>();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlimentos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBebidas = new javax.swing.JTextArea();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblAlimentos = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        btnEnviarCocina = new javax.swing.JButton();
        btnEnviarBar = new javax.swing.JButton();
        btnRealizarPedido = new javax.swing.JButton();
        lblTotalPago = new javax.swing.JLabel();
        txtTotalPago = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(216, 219, 212));
        jPanel1.setPreferredSize(new java.awt.Dimension(1253, 700));

        cmbAlimentos.setBackground(new java.awt.Color(179, 194, 156));
        cmbAlimentos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbAlimentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comidas" }));
        cmbAlimentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbBebidas.setBackground(new java.awt.Color(179, 194, 156));
        cmbBebidas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebidas" }));
        cmbBebidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSplitPane1.setDividerLocation(350);

        txtAlimentos.setColumns(20);
        txtAlimentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAlimentos.setRows(5);
        jScrollPane1.setViewportView(txtAlimentos);

        jSplitPane1.setLeftComponent(jScrollPane1);

        txtBebidas.setColumns(20);
        txtBebidas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBebidas.setRows(5);
        jScrollPane2.setViewportView(txtBebidas);

        jSplitPane1.setRightComponent(jScrollPane2);

        lblNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNombreCliente.setText("Nombre del cliente");

        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lblAlimentos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblAlimentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlimentos.setText("Alimentos");

        lblBebidas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblBebidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBebidas.setText("Bebidas");

        btnEnviarCocina.setBackground(new java.awt.Color(180, 196, 158));
        btnEnviarCocina.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEnviarCocina.setText("Enviar a cocina");
        btnEnviarCocina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEnviarBar.setBackground(new java.awt.Color(179, 194, 156));
        btnEnviarBar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEnviarBar.setText("Enviar al bar");
        btnEnviarBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRealizarPedido.setBackground(new java.awt.Color(179, 194, 156));
        btnRealizarPedido.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnRealizarPedido.setText("Realizar pedido");
        btnRealizarPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTotalPago.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTotalPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPago.setText("Total a pagar");

        txtTotalPago.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lblAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(lblBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnEnviarCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(btnEnviarBar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(lblTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombreCliente)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAlimentos)
                                    .addComponent(lblBebidas))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(cmbAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPago)
                            .addComponent(txtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnviarBar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btnEnviarCocina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Pedido pedido = new Pedido();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Pedido().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarBar;
    private javax.swing.JButton btnEnviarCocina;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JComboBox<String> cmbAlimentos;
    private javax.swing.JComboBox<String> cmbBebidas;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAlimentos;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTotalPago;
    private javax.swing.JTextArea txtAlimentos;
    private javax.swing.JTextArea txtBebidas;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTotalPago;
    // End of variables declaration//GEN-END:variables
}
