package interfazMesero;

import Mesero.Order;

/**
 *
 * @author Jorshua Solorzano
 */
public class ShakesMenu extends javax.swing.JInternalFrame {
    private String selectedShakes;
    private int quantityShakes;
    private Order Order;
    
    public ShakesMenu() {
        super("Menú de batidos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbShakes = new javax.swing.JComboBox<>();
        spnShakes = new javax.swing.JSpinner();
        lblShakes = new javax.swing.JLabel();
        btnPrintShakes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(455, 657));

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbShakes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Batido de piña", "Batido de fresa", "Batido de mora", "Batido de banano" }));
        cmbShakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShakesActionPerformed(evt);
            }
        });

        spnShakes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblShakes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShakes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShakes.setText("Batidos");

        btnPrintShakes.setText("Imprimir pedido");
        btnPrintShakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintShakesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(cmbShakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnShakes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblShakes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnPrintShakes)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblShakes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbShakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnShakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(btnPrintShakes)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbShakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShakesActionPerformed

    }//GEN-LAST:event_cmbShakesActionPerformed

    private void btnPrintShakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintShakesActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        selectedShakes = (String) cmbShakes.getSelectedItem();
        quantityShakes = (int) spnShakes.getValue();

        // Verificar si el JFrame InterPedido ya está creado
        if (Order != null) {
            // Construir el text a agregar
            String text = "Bibidas alcoholicas seleccionadas: " + selectedShakes + "\n";
            text += "Cantidad de bebidas alcoholicas: " + quantityShakes + "\n";

            // Agregar el text al JTextArea txtPedido en el JFrame InterPedido
            Order.addText(text);
        }
    }//GEN-LAST:event_btnPrintShakesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintShakes;
    private javax.swing.JComboBox<String> cmbShakes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblShakes;
    private javax.swing.JSpinner spnShakes;
    // End of variables declaration//GEN-END:variables
}
