/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Restaurant;

/**
 *
 * @author james
 */
public class loginFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        pnlLogin = new javax.swing.JPanel();
        lbUser = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        passfAcount = new javax.swing.JPasswordField();
        tfUser = new javax.swing.JTextField();
        lbWelcome = new javax.swing.JLabel();
        lbUserImg = new javax.swing.JLabel();
        btnLogin = new javax.swing.JToggleButton();
        lbBackgroundLog = new javax.swing.JLabel();
        lbBackgroundFrame = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        pnlLogin.setMaximumSize(new java.awt.Dimension(1920, 1080));
        pnlLogin.setMinimumSize(new java.awt.Dimension(1920, 1080));
        pnlLogin.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUser.setFont(new java.awt.Font("Agency FB", 0, 40)); // NOI18N
        lbUser.setText("Usuario");
        pnlLogin.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 344, 46));

        lbPassword.setFont(new java.awt.Font("Agency FB", 0, 40)); // NOI18N
        lbPassword.setText("Contraseña");
        pnlLogin.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 344, -1));

        passfAcount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passfAcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfAcountActionPerformed(evt);
            }
        });
        pnlLogin.add(passfAcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 344, 55));

        tfUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        pnlLogin.add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 344, 55));

        lbWelcome.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lbWelcome.setText("Bienvenido");
        pnlLogin.add(lbWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, -1, 90));

        lbUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emoployer.png"))); // NOI18N
        pnlLogin.add(lbUserImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 130, 120));

        btnLogin.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 630, 100, 40));

        lbBackgroundLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Difuminado 1_1.jpg"))); // NOI18N
        lbBackgroundLog.setText("jLabel4");
        lbBackgroundLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbBackgroundLog.setMaximumSize(new java.awt.Dimension(1122, 1000));
        pnlLogin.add(lbBackgroundLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 570, 830));

        lbBackgroundFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo-azul.jpg"))); // NOI18N
        lbBackgroundFrame.setText("jLabel7");
        lbBackgroundFrame.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlLogin.add(lbBackgroundFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -180, 2340, 1210));

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 2100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
       tfUser.setText("hola");
    }//GEN-LAST:event_tfUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        systemLog();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void passfAcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfAcountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfAcountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    public void systemLog(){
  
String user = tfUser.getText();

String password = String.valueOf(passfAcount.getPassword());




    if ((user.equals("A"))&&(password.compareTo("1")==0)) {
        
//JOptionPane.showMessageDialog(null,"Bienvenido al Sistema");
WaiterFrame form = new WaiterFrame();
        form.setVisible(true);
        
     
        this.dispose();
    } else {
//         JOptionPane.showMessageDialog(null,"Error vuelva a intentarlo"); 
         tfUser.setText("");
         passfAcount.setText(null);
    }
}
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lbBackgroundFrame;
    private javax.swing.JLabel lbBackgroundLog;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUserImg;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JPasswordField passfAcount;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}

