package waiterInterface;

import waiterInterface.Order;
/**
 *
 * @author Jorshua Solorzano
 */
public class MenuMainDishes extends javax.swing.JInternalFrame {

    private String selectedMainDishes;
    private int quantityMainDishes;
    private Order Order;

    public MenuMainDishes() {
         super("Menú de platos fuertes");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbMainDishes = new javax.swing.JComboBox<>();
        spnMainDishes = new javax.swing.JSpinner();
        lblMainDishes = new javax.swing.JLabel();
        btnPrintMainDishes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setFocusable(false);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(455, 657));

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbMainDishes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Arroz con pollo", "Arroz con camarones", "Casado de carne en salsa", "Casado de chuleta de cerdo", "Filete de pollo a la plancha", "Bistec de res encebollado", "Filete de pescado con papas", "Costilla de Cerdo con salsa BBQ", "Alitas de Pollo con salsa BBQ", "Hamburguesa sencilla", "Hamburguesa con papas ", "Macarrones con salsa y bolitas de carne", "Macarrones en salsa blanca con pollo" }));
        cmbMainDishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMainDishesActionPerformed(evt);
            }
        });

        spnMainDishes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblMainDishes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMainDishes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainDishes.setText("Platos fuertes");

        btnPrintMainDishes.setText("Imprimir pedido");
        btnPrintMainDishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintMainDishesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spnMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(btnPrintMainDishes)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(btnPrintMainDishes)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMainDishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMainDishesActionPerformed

    }//GEN-LAST:event_cmbMainDishesActionPerformed

    private void btnPrintMainDishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintMainDishesActionPerformed

        // Obtener el desayuno seleccionado y la cantidad del JComboBox y el JSpinner, respectivamente
        selectedMainDishes = (String) cmbMainDishes.getSelectedItem();
        quantityMainDishes = (int) spnMainDishes.getValue();

        // Verificar si el JFrame InterPedido ya está creado
        if (Order != null) {
            // Construir el text a agregar
            String text = "Plato fuerte seleccionado: " + selectedMainDishes + "\n";
            text += "Cantidad de platos fuertes: " + quantityMainDishes + "\n";

            // Agregar el text al JTextArea txtPedido en el JFrame InterPedido
            Order.addText(text);
        }
    }//GEN-LAST:event_btnPrintMainDishesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintMainDishes;
    private javax.swing.JComboBox<String> cmbMainDishes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMainDishes;
    private javax.swing.JSpinner spnMainDishes;
    // End of variables declaration//GEN-END:variables
}
