package Waiter;

import static Waiter.Order.txtOrder;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 * Este JInternal frame se encarga de mostrar el menú de bebidas alcoholicas,
 * aquí se van a gestionar las bebidas alcoholicas escogidas y su cantidad.
 *
 * @author Jorshua Solórzano
 */
public class AlcoholicDrinksMenu extends javax.swing.JInternalFrame {

    public AlcoholicDrinksMenu() {
        // Establecer el título de la ventana
        super("Menú de bebidas alcoholicas");
        initComponents();
//        atributes();
    }

    public void saveOrder(JTextArea txtOrder) {
        // Obtener el desayuno seleccionado y la cantidad del JComboBox cmbAlcoholicDrinks y el JSpinner spnAlcoholicDrinks, respectivamente.
        String selectedAlcoholicDrinks = (String) cmbAlcoholicDrinks.getSelectedItem();
        int quantityAlcoholicDrinks = (int) spnAlcoholicDrinks.getValue();

        // Verificar si se ha seleccionado una opción válida en el JComboBox cmbAlcoholicDrinks y el JSpinner spnAlcoholicDrinks.
        if (selectedAlcoholicDrinks.equals("Elegir...") || quantityAlcoholicDrinks == 0) {
            // Mostrar un mensaje de error 
            JOptionPane.showMessageDialog(null, "Debe seleccionar una opción válida");
            return; // Salir del método sin guardar el pedido
        }

        // Construir el texto a guardar
        StringBuilder textBuilder = new StringBuilder("Pedido para mesa: ");
        //Guardar las opciones de bebidas alcoholicas seleccionadas que sean validas.
        if (!selectedAlcoholicDrinks.equals("Elegir...")) {
            textBuilder.append(selectedAlcoholicDrinks).append(", ");
        }
        //Guardar las cantidades de bebidas alcoholicas seleccionadas que sean validas.
        if (quantityAlcoholicDrinks != 0) {
            textBuilder.append(quantityAlcoholicDrinks);
        }

        String text = textBuilder.toString() + "\n";

        // Agregar la información al txtOrder del JInternal frame Order
        txtOrder.append(text);

        //Guardar como nuevo pedido
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Order.txt", true))) {
            writer.write(text);
            writer.newLine();
        } catch (IOException e) {
        }
        //Guardar en los pedidos que van para la bar
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Bar.txt", true))) {
            writer.write(text);
            writer.newLine();
        } catch (IOException e) {
        }

        //Guardar los datos en el historial del punto de venta
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Historial.txt", true))) {
            writer.write(text);
        } catch (IOException e) {
        }

        // Vaciar el contenido del archivo para darle campo al siguiente pedido
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Order.txt", false))) {
            writer.write(" ");
        } catch (IOException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAlcoholicDrinks = new javax.swing.JComboBox<>();
        spnAlcoholicDrinks = new javax.swing.JSpinner();
        lblAlcoholicDrinks = new javax.swing.JLabel();
        btnAddMD = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(455, 657));

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 536));
        jPanel1.setRequestFocusEnabled(false);

        cmbAlcoholicDrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir..." }));
        cmbAlcoholicDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlcoholicDrinksActionPerformed(evt);
            }
        });

        spnAlcoholicDrinks.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        lblAlcoholicDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAlcoholicDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlcoholicDrinks.setText("Bebidas alcoholicas");

        btnAddMD.setText("Agregar al pedido");
        btnAddMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAddMD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(cmbAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAlcoholicDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(btnAddMD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlcoholicDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlcoholicDrinksActionPerformed

    }//GEN-LAST:event_cmbAlcoholicDrinksActionPerformed
    //Tiene la funcionabilidad de guardar el pedido
    private void btnAddMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMDActionPerformed
        saveOrder(txtOrder);
    }//GEN-LAST:event_btnAddMDActionPerformed

//    public void atributes() {
//        MealMap mealmap = new MealMap();
//        String filter = "BA";
//        try {
//            mealmap.filtrarPorCodigo(filter, cmbAlcoholicDrinks, spnAlcoholicDrinks);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(BreakFastMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddMD;
    private javax.swing.JComboBox<String> cmbAlcoholicDrinks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlcoholicDrinks;
    private javax.swing.JSpinner spnAlcoholicDrinks;
    // End of variables declaration//GEN-END:variables
}
