/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AdminInterface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Cesar
 */
public class InterfaceChargeMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterfaceChargeMenu
     */
    public InterfaceChargeMenu() {
        initComponents();
        /**
         * Para cesar men meti su codigo en una funcion para llamarla cuando ocupe cargar la lista del inventario
         * tambien recuerde que no debemos meter logica pura en los botones recuerde usar funciones 
         * y ya no se ocupa usar el jfile chooser 
         * 
         * 
         * 
         */
         
     loadInventory();
    }
/**
 * This method has the function of loading the inventory from the txt
 */
    public void loadInventory() {
        // Leer el contenido del archivo
        try {
            BufferedReader reader = new BufferedReader(new FileReader("InventariosAdmin.txt"));
            String line;
            StringBuilder content = new StringBuilder();
            while ((line = reader.readLine()) != null) {
                content.append(line).append("\n");
            }
            reader.close();
            // Hacer algo con el contenido del archivo (por ejemplo, mostrarlo en un JTextArea)
            taShowMenu.setText(content.toString());
        } catch (IOException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BgPanel = new javax.swing.JPanel();
        BorderPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lblMenuCharge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taShowMenu = new javax.swing.JTextArea();
        btnMenuElection = new javax.swing.JButton();
        lblChargeMenu = new javax.swing.JLabel();
        btnSaveElection = new javax.swing.JButton();
        lblSaveElecction1 = new javax.swing.JLabel();
        btnDeleteElection = new javax.swing.JButton();
        lblDeleteElecction = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BorderPanel.setBackground(new java.awt.Color(51, 51, 51));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminInterface/salida.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblMenuCharge.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMenuCharge.setForeground(new java.awt.Color(0, 153, 153));
        lblMenuCharge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuCharge.setText("Cargar Menu");
        lblMenuCharge.setOpaque(true);

        javax.swing.GroupLayout BorderPanelLayout = new javax.swing.GroupLayout(BorderPanel);
        BorderPanel.setLayout(BorderPanelLayout);
        BorderPanelLayout.setHorizontalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(lblMenuCharge)
                .addGap(240, 240, 240))
        );
        BorderPanelLayout.setVerticalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addComponent(lblMenuCharge)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        taShowMenu.setColumns(20);
        taShowMenu.setRows(5);
        taShowMenu.setText("\t\t\t      Menu del dia");
        jScrollPane1.setViewportView(taShowMenu);

        btnMenuElection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminInterface/carga-de-carpeta (1).png"))); // NOI18N
        btnMenuElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuElectionActionPerformed(evt);
            }
        });

        lblChargeMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblChargeMenu.setText("Cargar menu");

        btnSaveElection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminInterface/flecha-de-circulo-de-disquete-a-la-derecha.png"))); // NOI18N
        btnSaveElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveElectionActionPerformed(evt);
            }
        });

        lblSaveElecction1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSaveElecction1.setText("Guardar eleccion");

        btnDeleteElection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminInterface/circulo-de-basura.png"))); // NOI18N
        btnDeleteElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteElectionActionPerformed(evt);
            }
        });

        lblDeleteElecction.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDeleteElecction.setText("Borrar eleccion ");

        javax.swing.GroupLayout BgPanelLayout = new javax.swing.GroupLayout(BgPanel);
        BgPanel.setLayout(BgPanelLayout);
        BgPanelLayout.setHorizontalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(BgPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaveElecction1)
                    .addGroup(BgPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenuElection, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChargeMenu)
                            .addComponent(btnSaveElection, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteElection, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDeleteElecction))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BgPanelLayout.setVerticalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPanelLayout.createSequentialGroup()
                .addComponent(BorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BgPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnMenuElection, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblChargeMenu)
                        .addGap(13, 13, 13)
                        .addComponent(btnSaveElection)
                        .addGap(0, 0, 0)
                        .addComponent(lblSaveElecction1)
                        .addGap(23, 23, 23)
                        .addComponent(btnDeleteElection, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblDeleteElecction))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveElectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveElectionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ActionListener closeSystem = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Cierra la ventana actual
            }
        };
        // Asignar el detector de acción al botón
        btnExit.addActionListener(closeSystem);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDeleteElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteElectionActionPerformed
        taShowMenu.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteElectionActionPerformed

    private void btnMenuElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuElectionActionPerformed

        loadInventory();


    }//GEN-LAST:event_btnMenuElectionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel;
    private javax.swing.JPanel BorderPanel;
    private javax.swing.JButton btnDeleteElection;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMenuElection;
    private javax.swing.JButton btnSaveElection;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChargeMenu;
    private javax.swing.JLabel lblDeleteElecction;
    private javax.swing.JLabel lblMenuCharge;
    private javax.swing.JLabel lblSaveElecction1;
    private javax.swing.JTextArea taShowMenu;
    // End of variables declaration//GEN-END:variables
}
